server:
  port: 8889

spring:
  datasource:
    username: root
    password: lykang2000
    url: jdbc:mysql://chi1t0n.com:3306/monitoring?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.uestc.monitor.pojo

#showSql
logging:
  level:
    com:
      example:
        mapper : debug